spring:
  application:
    name: notification-service
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/notification_service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${EMAIL.HOST}
    username: ${EMAIL.USERNAME}
    password: ${EMAIL.PASSWORD}
    port: ${EMAIL.PORT}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true


settings:
  jwt:
    secret: a7b49f2c628facf950bffe6f734ec3158c9eebc40d2c68089ca3505ce8cde38c
    accessLifetime: 24h
    refreshLifetime: 48h
  twilio:
    accountSid: ${TWILIO.SID}
    authToken: ${TWILIO.TOKEN}
    number: ${TWILIO.NUMBER}
    whatsapp-number: ${TWILIO.WHATSAPP_NUMBER}
