name: Run tests and build application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7777
          POSTGRES_DB: notification_service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up environment variables
        run: echo "TWILIO_SID=${{ secrets.TWILIO_SID }}" >> $GITHUB_ENV
          && echo "TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }}" >> $GITHUB_ENV
          && echo "TWILIO_NUMBER=${{ secrets.TWILIO_NUMBER }}" >> $GITHUB_ENV
          && echo "TWILIO_WHATSAPP_NUMBER=${{ secrets.TWILIO_WHATSAPP_NUMBER }}" >> $GITHUB_ENV
          && echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
          && echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
          && echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          && echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV

      - name: Run tests
        run: cd notification-service && mvn test

      - name: Build application
        run: cd notification service && docker build -t notification-service .