name: Run tests and build application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7777
          POSTGRES_DB: notification_service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run tests
        run: mvn test

      - name: Build application
        run: docker build -t notification-service .